# Generated by Django 3.2.7 on 2021-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writersName', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=2000)),
                ('isAcceptable', models.BooleanField()),
                ('whichImageID', models.CharField(max_length=20)),
                ('audioLink', models.CharField(max_length=300)),
                ('commentID', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageAddress', models.CharField(max_length=200)),
                ('imageID', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storiesText', models.CharField(max_length=2000)),
                ('audioLink', models.CharField(max_length=300)),
                ('storieID', models.CharField(max_length=40)),
            ],
        ),
    ]
